# Generated by Django 5.0.7 on 2024-10-07 09:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comité/scome', verbose_name="Image de l'évènement")),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comité/scope', verbose_name="Image de l'évènement")),
            ],
        ),
        migrations.CreateModel(
            name='Scoph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comité/scoph', verbose_name="Image de l'évènement")),
            ],
        ),
        migrations.CreateModel(
            name='Scora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comité/scora', verbose_name="Image de l'évènement")),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comité/score', verbose_name="Image de l'évènement")),
            ],
        ),
        migrations.CreateModel(
            name='Scorp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='comité/scorp', verbose_name="Image de l'évènement")),
            ],
        ),
        migrations.CreateModel(
            name='Actualité',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name="Titre de l'évènement")),
                ('content', ckeditor.fields.RichTextField(verbose_name="Contenu (Veillez à bien rediger et structurer l'article) :")),
                ('image', models.ImageField(blank=True, upload_to='actu', verbose_name="Image de l'évènement")),
                ('files', models.FileField(blank=True, upload_to='actu/', verbose_name='Fichier associé (Pdf, Images, vidéo, etc)')),
                ('link', models.URLField(blank=True, verbose_name="Lien de l'évènement")),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creation'],
                'indexes': [models.Index(fields=['-creation'], name='core_actual_creatio_579dbc_idx')],
            },
        ),
    ]
