# Generated by Django 5.0.7 on 2024-09-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.CharField(max_length=255, verbose_name='titre et descripton du media')),
                ('url', models.URLField(verbose_name='Lien du drive')),
            ],
        ),
    ]
