# Generated by Django 5.0.7 on 2024-09-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.ImageField(default=1, upload_to='mediathèque', verbose_name='Images du media (au moins une image representative)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='link',
            field=models.URLField(default=2, verbose_name='Lien drive du media'),
            preserve_default=False,
        ),
    ]
