# Generated by Django 5.0.7 on 2024-10-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0002_remove_media_url_media_image_media_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, upload_to='mediathèque', verbose_name='Images du media (au moins une image representative)'),
        ),
    ]
