# Generated by Django 5.0.7 on 2024-10-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0003_alter_media_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='fichier',
            new_name='titre',
        ),
    ]
