# Generated by Django 5.0.7 on 2024-10-05 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediatheque', '0004_rename_fichier_media_titre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['-titre']},
        ),
    ]
