# Generated by Django 5.0.7 on 2024-10-07 09:45

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('resume', models.TextField(max_length=500, verbose_name='Resumé')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Contenu (Veillez à bien rediger et structurer l'article) :")),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('image', models.ImageField(upload_to='blog/post_image', verbose_name="Image de l'article")),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='blog_articl_created_a349a7_idx')],
            },
        ),
    ]
