# Generated by Django 5.0.7 on 2024-10-07 09:45

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Titre')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
                ('resume', models.TextField(verbose_name="Resumé de l'article :")),
                ('content', ckeditor.fields.RichTextField(verbose_name="Contenu (Veillez à bien rediger et structurer l'article) :")),
                ('image', models.ImageField(upload_to='protocol/', verbose_name='Image')),
                ('source', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
