# Generated by Django 5.0.7 on 2024-10-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='INSSA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Nom et prenom(s) de membre du bureau')),
                ('post', models.TextField(max_length=255, verbose_name='Poste du membre du bureau')),
                ('photo', models.ImageField(blank=True, upload_to='office/inssa/', verbose_name='Photo du membre du bureau')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Lien LinkedIn du membre du bureau')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='office_inss_created_6beebd_idx')],
            },
        ),
        migrations.CreateModel(
            name='National',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Nom et prenom(s) de membre du bureau')),
                ('post', models.TextField(max_length=255, verbose_name='Poste du membre du bureau')),
                ('photo', models.ImageField(blank=True, upload_to='office/national/', verbose_name='Photo du membre du bureau')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Lien LinkedIn du membre du bureau')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='office_nati_created_faeb44_idx')],
            },
        ),
        migrations.CreateModel(
            name='UJKZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Nom et prenom(s) de membre du bureau')),
                ('post', models.TextField(max_length=255, verbose_name='Poste du membre du bureau')),
                ('photo', models.ImageField(blank=True, upload_to='office/ujkz/', verbose_name='Photo du membre du bureau')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Lien LinkedIn du membre du bureau')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='office_ujkz_created_ad4205_idx')],
            },
        ),
        migrations.CreateModel(
            name='UOHG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Nom et prenom(s) de membre du bureau')),
                ('post', models.TextField(max_length=255, verbose_name='Poste du membre du bureau')),
                ('photo', models.ImageField(blank=True, upload_to='office/uohg/', verbose_name='Photo du membre du bureau')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Lien LinkedIn du membre du bureau')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='office_uohg_created_dbe3bd_idx')],
            },
        ),
        migrations.CreateModel(
            name='USDAO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Nom et prenom(s) de membre du bureau')),
                ('post', models.TextField(max_length=255, verbose_name='Poste du membre du bureau')),
                ('photo', models.ImageField(blank=True, upload_to='office/usdao/', verbose_name='Photo du membre du bureau')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Lien LinkedIn du membre du bureau')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='office_usda_created_dc2c9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='USTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Nom et prenom(s) de membre du bureau')),
                ('post', models.TextField(max_length=255, verbose_name='Poste du membre du bureau')),
                ('photo', models.ImageField(blank=True, upload_to='office/usta/', verbose_name='Photo du membre du bureau')),
                ('link', models.URLField(blank=True, max_length=500, verbose_name='Lien LinkedIn du membre du bureau')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='office_usta_created_3ba128_idx')],
            },
        ),
    ]
